DROP TABLE IF EXISTS COCHES;
DROP TABLE IF EXISTS MARCAS;
DROP TABLE IF EXISTS PRECIOS;

CREATE TABLE COCHES
(
    ID            INT AUTO_INCREMENT PRIMARY KEY,
    ID_MARCA      INT          NOT NULL,
    NOMBRE_MODELO VARCHAR(250) NOT NULL,
    COLOR         VARCHAR(50)
);

CREATE TABLE MARCAS
(
    ID           INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_MARCA VARCHAR(250) NOT NULL
);

CREATE TABLE PRECIOS
(
    ID           INT AUTO_INCREMENT PRIMARY KEY,
    ID_COCHE     INT NOT NULL,
    FECHA_INICIO DATE,
    FECHA_FIN    DATE,
    PRECIO       INT NOT NULL
);
